### ISSUE TITLE
File operations

### ISSUE THREAD

**Issue by luca020400** [SebaUbuntu/android_packages_apps_Gallery#13]
Single file
|Feature|Status|
|-------|------|
|Deletion|✔️|
|Sharing|✔️|
|Editing|✔️|

Multi file
|Feature|Status|
|-------|------|
|Deletion|✔️|
|Sharing|✔️|

**Comment by luk1337** [comment]
Hard: editing

**Comment by luk1337** [comment]
Also I think we should have an option to strip exif ^.^

**Comment by luca020400** [comment]
> Also I think we should have an option to strip exif ^.^

Can likely have different share variants with/without exif
